version: "3"

services:
  email:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG4JS_CONFIG: ./conf/logging.default.json
    command: npm run start-dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
